apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}

  artifacts:

  - image: us-central1-docker.pkg.dev/uberscott/uberscott/uberscott
    context: uberscott.com
  - image: us-central1-docker.pkg.dev/uberscott/uberscott/starlane
    context: starlane.io


deploy:
  helm:
    flags:

    releases:
    - name: uberscott
      namespace: uberscott
      chartPath: uberscott.com/helm
      values:
        uberscott: us-central1-docker.pkg.dev/uberscott/uberscott/uberscott

    - name: starlane
      namespace: uberscott
      chartPath: starlane.io/helm
      values:
        uberscott: us-central1-docker.pkg.dev/uberscott/uberscott/starlane




