apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}

  artifacts:

  - image: us-central1-docker.pkg.dev/uberscott/uberscott/uberscott
    context: uberscott.com
  - image: us-central1-docker.pkg.dev/uberscott/uberscott/starlane
    context: starlane.io
  - image: us-central1-docker.pkg.dev/uberscott/uberscott/punchline
    context: punch-line.app


deploy:
  helm:
    flags:

    releases:
    - name: uberscott
      namespace: uberscott
      chartPath: uberscott.com/helm
      values:
        uberscott: us-central1-docker.pkg.dev/uberscott/uberscott/uberscott

    - name: starlane
      namespace: starlane 
      chartPath: starlane.io/helm
      values:
        starlane: us-central1-docker.pkg.dev/uberscott/uberscott/starlane

    - name: punchline
      namespace: punchline
      chartPath: punch-line.app/helm
      values:
        punchline: us-central1-docker.pkg.dev/uberscott/uberscott/punchline



