apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}

  artifacts:

  - image: us-central1-docker.pkg.dev/uberscott/uberscott/uberscott
    context: uberscott.com

deploy:
  helm:
    flags:

    releases:
    - name: uberscott
      namespace: scott
      chartPath: helm
      values:
        uberscott: us-central1-docker.pkg.dev/uberscott/uberscott/uberscott


