apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}

  artifacts:

  - image: docker.io/uberscott/uberscott.com
    context: uberscott.com

  - image: docker.io/uberscott/mightydevco
    context: mightydevco.com


deploy:
  helm:
    flags:

    releases:
    - name: uberscott
      namespace: scott
      chartPath: helm
      values:
        uberscott: docker.io/uberscott/uberscott.com
        mightydevco: docker.io/uberscott/mightydevco


