apiVersion: v1
kind: Service
metadata:
  name: mightydevco
  labels:
    app.kubernetes.io/name: mightydevco
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mightydevco
    app.kubernetes.io/instance: {{ .Release.Name }}
