
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uberscott
  annotations:
    kubernetes.io/ingress.global-static-ip-name: uberscott2
    networking.gke.io/managed-certificates: uberscott
    kubernetes.io/ingress.class: "gce"  
spec:
  ingressClassName: "gce"
  defaultBackend:
    service:
      name: uberscott-nodeport
      port:
        number: 80
