apiVersion: v1
kind: Service
metadata:
  name: uberscott
  labels:
    app.kubernetes.io/name: uberscott
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  #loadBalancerIP: "35.224.94.191"
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: uberscott
    app.kubernetes.io/instance: {{ .Release.Name }}
