apiVersion: v1
kind: Service
metadata:
  name: punchline
  labels:
    app.kubernetes.io/name: punchline
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: punchline
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

