apiVersion: v1
kind: Service
metadata:
  name: uberscott
  namespace: uberscott
spec:
  selector:
    app: uberscott
  type: LoadBalancer 
  loadBalancerIP: 34.134.138.246
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
