apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: astrobattle
  namespace: astrobattle
  labels:
    app.kubernetes.io/name: astrobattle
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  domains:
    - astrobattle.com
